import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Head from "next/head";

// Components
import Nav from "./components/nav";

<Head>
  <link rel="icon" type="image/png" href="logo/logoIcon2.png"/>           
</Head>

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MiniCrit",
  description: "Generated by create next app",
  icons: {
    icon: "logo/logoIcon2.png",
  },
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">  
      <body>
        <Nav />
        {children}
      </body>
    </html>
  );
}
