import type { Metadata } from "next";
import "./globals.css";
import Head from "next/head";

// Components
import Nav from "./components/layout/nav";

<Head>
  <link rel="icon" type="image/png" href="/logo/logoIcon2.png"/>           
</Head>

export const metadata: Metadata = {
  title: "MiniCrit",
  description: "Generated by create next app",
  icons: {
    icon: "/logo/logoIcon2.png",
  },
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">  
      <body>
        <Nav />
        {children}
      </body>
    </html>
  );
}
