export const runtime = 'nodejs'
export const dynamic = 'force-dynamic';

import type { Metadata } from "next";
import "./globals.css";

// Components
import NavServer from "../components/server/navServer"
import Footer from "../components/layout/footer";

export const metadata: Metadata = {
  title: "MiniCrit",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: "/logo/logoIcon2.png", media: "(prefers-color-scheme: dark)" },
      { url: "/logo/logoIcon1.png", media: "(prefers-color-scheme: light)" },
    ],
  },
};


export default async function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en" className="no-scrollbar">
      <body className="no-scrollbar overflow-y-scroll overflow-x-hidden w-screen h-screen">
        <NavServer/>
        {children}
        <Footer />
      </body>
    </html>
  );
}