import type { Metadata } from "next";
import "./globals.css";

// Components
import Nav from "../components/layout/nav";
import Footer from "../components/layout/footer";


export const metadata: Metadata = {
  title: "MiniCrit",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: "/logo/logoIcon2.png", media: "(prefers-color-scheme: dark)" },
      { url: "/logo/logoIcon1.png", media: "(prefers-color-scheme: light)" },
    ],
  },
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en" className="no-scrollbar">
      <body className="no-scrollbar overflow-y-scroll overflow-x-hidden">
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}