import type { Metadata } from "next";
import "./globals.css";

import { selectUser } from "@/lib/users"

// Components
import Nav from "../components/layout/nav";
import Footer from "../components/layout/footer";

export const metadata: Metadata = {
  title: "MiniCrit",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: "/logo/logoIcon2.png", media: "(prefers-color-scheme: dark)" },
      { url: "/logo/logoIcon1.png", media: "(prefers-color-scheme: light)" },
    ],
  },
};

export default async function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  const user = await selectUser("");

  return (
    <html lang="en" className="no-scrollbar">
      <body className="no-scrollbar overflow-y-scroll overflow-x-hidden">
        <Nav user={user} />
        {children}
        <Footer />
      </body>
    </html>
  );
}